/* Browser-only BMI calculator. History and theme preferences stay on this device. */
const keys = { history: "vital-measure-history", theme: "vital-measure-theme" };
const maxHistory = 8;
const el = {
  form: document.querySelector("#bmi-form"), unitButtons: document.querySelectorAll(".unit-button"), metric: document.querySelector("#metric-fields"), imperial: document.querySelector("#imperial-fields"), error: document.querySelector("#input-error"), reset: document.querySelector("#reset-button"), theme: document.querySelector("#theme-toggle"), resultPanel: document.querySelector("#result-panel"), resultEmpty: document.querySelector("#result-empty"), resultContent: document.querySelector("#result-content"), resultSymbol: document.querySelector("#result-symbol"), resultLabel: document.querySelector("#result-label"), bmi: document.querySelector("#bmi-value"), category: document.querySelector("#result-category"), note: document.querySelector("#result-note"), range: document.querySelector("#healthy-range"), marker: document.querySelector("#range-marker"), markerValue: document.querySelector("#marker-value"), download: document.querySelector("#download-card"), historyList: document.querySelector("#history-list"), clearHistory: document.querySelector("#clear-history"), heightCm: document.querySelector("#height-cm"), weightKg: document.querySelector("#weight-kg"), feet: document.querySelector("#height-feet"), inches: document.querySelector("#height-inches"), pounds: document.querySelector("#weight-pounds"),
};
const categories = {
  underweight: { name: "Underweight", label: "Below the usual range", note: "Your result falls below the standard adult BMI range.", color: "#6A9BB5", symbol: "↓" },
  healthy: { name: "Healthy range", label: "Within the usual range", note: "Your result falls within the standard adult BMI range.", color: "#4E8A63", symbol: "●" },
  overweight: { name: "Overweight", label: "Above the usual range", note: "Your result falls above the standard adult BMI range.", color: "#D39A43", symbol: "↑" },
  obesity: { name: "Obesity", label: "Well above the usual range", note: "Your result falls well above the standard adult BMI range.", color: "#C76B59", symbol: "↑" },
};
let unit = "metric";
let latest = null;
const number = (input) => Number(input.value);
function read(key, fallback) { try { return JSON.parse(localStorage.getItem(key)) ?? fallback; } catch { return fallback; } }
function write(key, value) { try { localStorage.setItem(key, JSON.stringify(value)); } catch { /* Storage is optional. */ } }
function dateLabel(value) { return new Intl.DateTimeFormat(undefined, { month: "short", day: "numeric", year: "numeric" }).format(new Date(value)); }
function getCategory(value) { if (value < 18.5) return categories.underweight; if (value < 25) return categories.healthy; if (value < 30) return categories.overweight; return categories.obesity; }
function measurement() {
  if (unit === "metric") { const cm = number(el.heightCm), kg = number(el.weightKg); if (!cm || !kg || cm < 80 || cm > 250 || kg < 20 || kg > 500) return null; const metres = cm / 100; return { bmi: kg / metres ** 2, metres, display: `${cm} cm · ${kg} kg` }; }
  const feet = number(el.feet), inches = Number(el.inches.value || 0), pounds = number(el.pounds), totalInches = feet * 12 + inches;
  if (!feet || feet < 3 || feet > 8 || inches < 0 || inches > 11 || !pounds || pounds < 45 || pounds > 1100) return null;
  return { bmi: (pounds / totalInches ** 2) * 703, metres: totalInches * 0.0254, display: `${feet}′ ${inches}″ · ${pounds} lb` };
}
function resetResult() { latest = null; el.error.classList.add("is-hidden"); el.resultPanel.classList.remove("is-result"); el.resultContent.classList.add("is-hidden"); el.resultEmpty.classList.remove("is-hidden"); el.marker.classList.remove("is-visible"); }
function selectUnit(next) { unit = next; el.unitButtons.forEach((button) => { const selected = button.dataset.unit === next; button.classList.toggle("selected", selected); button.setAttribute("aria-pressed", String(selected)); }); el.metric.classList.toggle("is-hidden", next !== "metric"); el.imperial.classList.toggle("is-hidden", next !== "imperial"); resetResult(); }
function makeResult(input) { const bmi = Number(input.bmi.toFixed(1)), category = getCategory(bmi), low = 18.5 * input.metres ** 2, high = 24.9 * input.metres ** 2; return { bmi, category, healthyRange: unit === "metric" ? `${low.toFixed(1)}–${high.toFixed(1)} kg` : `${(low * 2.20462).toFixed(0)}–${(high * 2.20462).toFixed(0)} lb`, marker: Math.min(96, Math.max(4, ((bmi - 14) / 24) * 100)), measurement: input.display, date: Date.now() }; }
function renderHistory() { const history = read(keys.history, []); el.historyList.textContent = ""; el.clearHistory.classList.toggle("is-hidden", !history.length); if (!history.length) { const item = document.createElement("li"); item.className = "empty-history"; item.textContent = "Your calculations will appear here after you calculate a BMI."; el.historyList.append(item); return; } history.forEach((entry) => { const item = document.createElement("li"), dot = document.createElement("span"), score = document.createElement("strong"), details = document.createElement("span"), title = document.createElement("b"), subtitle = document.createElement("small"); item.className = "history-item"; dot.className = "history-dot"; dot.style.background = entry.color; score.textContent = entry.bmi.toFixed(1); details.className = "history-details"; title.textContent = entry.name; subtitle.textContent = `${entry.measurement} · ${dateLabel(entry.date)}`; details.append(title, subtitle); item.append(dot, score, details); el.historyList.append(item); }); }
function saveHistory(result) { const history = read(keys.history, []); history.unshift({ bmi: result.bmi, name: result.category.name, color: result.category.color, measurement: result.measurement, date: result.date }); write(keys.history, history.slice(0, maxHistory)); renderHistory(); }
function showResult(result) { latest = result; el.error.classList.add("is-hidden"); el.resultSymbol.textContent = result.category.symbol; el.resultSymbol.style.color = result.category.color; el.resultLabel.textContent = result.category.label; el.bmi.textContent = result.bmi.toFixed(1); el.category.textContent = result.category.name; el.category.style.color = result.category.color; el.note.textContent = result.category.note; el.range.textContent = result.healthyRange; el.markerValue.textContent = result.bmi.toFixed(1); el.marker.style.left = `${result.marker}%`; el.resultEmpty.classList.add("is-hidden"); el.resultContent.classList.remove("is-hidden"); el.resultPanel.classList.remove("is-result"); void el.resultPanel.offsetWidth; el.resultPanel.classList.add("is-result"); el.marker.classList.add("is-visible"); }
function downloadCard(result) { const canvas = document.createElement("canvas"), context = canvas.getContext("2d"), dark = document.body.dataset.theme === "dark", background = dark ? "#17251f" : "#f1ece1", ink = dark ? "#edf5ec" : "#254438", soft = dark ? "#293e34" : "#e0ebe0"; canvas.width = 1600; canvas.height = 900; context.fillStyle = background; context.fillRect(0, 0, 1600, 900); context.fillStyle = soft; context.beginPath(); context.arc(1410, -50, 330, 0, Math.PI * 2); context.fill(); context.fillStyle = result.category.color; context.fillRect(104, 110, 17, 17); context.fillStyle = ink; context.font = "700 28px Arial"; context.fillText("VITAL MEASURE", 150, 129); context.font = "600 24px Arial"; context.fillStyle = dark ? "#bfd1c1" : "#64766b"; context.fillText("PERSONAL HEALTH FIELD NOTE", 104, 239); context.font = "normal 62px Georgia"; context.fillStyle = ink; context.fillText("Body mass index", 104, 326); context.font = "normal 230px Georgia"; context.fillText(result.bmi.toFixed(1), 98, 580); context.font = "700 31px Arial"; context.fillStyle = result.category.color; context.fillText(result.category.name.toUpperCase(), 105, 650); context.font = "400 28px Arial"; context.fillStyle = dark ? "#c0d1c2" : "#51655a"; context.fillText(result.category.note, 105, 710); context.fillStyle = dark ? "#324d40" : "#d9e7da"; context.fillRect(1050, 420, 392, 190); context.font = "700 21px Arial"; context.fillStyle = dark ? "#b7cfbb" : "#587061"; context.fillText("USUAL WEIGHT RANGE", 1085, 476); context.font = "normal 48px Georgia"; context.fillStyle = ink; context.fillText(result.healthyRange, 1085, 545); context.font = "400 22px Arial"; context.fillStyle = dark ? "#b7cfbb" : "#587061"; context.fillText(`${result.measurement} · ${dateLabel(result.date)}`, 1085, 580); context.fillStyle = result.category.color; context.fillRect(104, 783, 1390, 12); const link = document.createElement("a"); link.download = `vital-measure-bmi-${result.bmi.toFixed(1)}.png`; link.href = canvas.toDataURL("image/png"); link.click(); }
function applyTheme(theme) { const dark = theme === "dark"; document.body.dataset.theme = dark ? "dark" : "light"; el.theme.setAttribute("aria-pressed", String(dark)); el.theme.setAttribute("aria-label", dark ? "Enable light mode" : "Enable dark mode"); el.theme.innerHTML = `<span aria-hidden="true">${dark ? "☀" : "☾"}</span><b>${dark ? "Light" : "Dark"}</b>`; try { localStorage.setItem(keys.theme, theme); } catch { /* Theme remains for this session. */ } }
el.unitButtons.forEach((button) => button.addEventListener("click", () => selectUnit(button.dataset.unit)));
el.form.addEventListener("submit", (event) => { event.preventDefault(); const input = measurement(); if (!input) { resetResult(); el.error.classList.remove("is-hidden"); return; } const result = makeResult(input); showResult(result); saveHistory(result); });
el.reset.addEventListener("click", () => { el.form.reset(); resetResult(); }); el.download.addEventListener("click", () => { if (latest) downloadCard(latest); }); el.clearHistory.addEventListener("click", () => { write(keys.history, []); renderHistory(); }); el.theme.addEventListener("click", () => applyTheme(document.body.dataset.theme === "dark" ? "light" : "dark")); document.querySelectorAll("input").forEach((input) => input.addEventListener("input", resetResult));
applyTheme(read(keys.theme, "light")); renderHistory();

